---
# ####################################################################
#                             Create cluster
# ####################################################################

- name: Create cluster {{ dapr_cluster_name }}
  include_tasks: ctlptl-create-cluster.yml
  tags:
    - create
    - create-test

# ####################################################################
#                             Delete cluster
# ####################################################################

- name: Create cluster {{ dapr_cluster_name }}
  include_tasks: delete-cluster.yml
  tags:
    - delete
