---
- name: Ensure correct context
  ansible.builtin.shell: kubectx kind-{{ dapr_cluster_name }}
  tags:
    - zipkin-install

- name: Ensure correct context finished
  debug:
    msg: 'Change kube context to {{ dapr_cluster_name }} finished.'
  tags:
    - zipkin-install
